/**
 * Copyright © 2017 Infest Developer Team.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 * * Neither the name of the copyright holder nor the names of its contributors
 *   may be used to endorse or promote products derived from this software 
 *   without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
package com.jogjadamai.infest.customer;

import com.jogjadamai.infest.comboboxmodel.TablesComboBoxModel;
import com.jogjadamai.infest.entity.Tables;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Danang Galuh Tegar P
 */
public class AskTableDialog extends javax.swing.JDialog {

    private final List<Tables> tableList;
    private final javax.swing.ComboBoxModel allTablesComboBoxModel;

    private Tables selectedTable = null;
    
    private static AskTableDialog INSTANCE;
    
    /**
     * Creates new form AskTableDialog
     * @param tableList
     * @return 
     */
    public static AskTableDialog getDialogInstance(List<Tables> tableList) {
        if(INSTANCE==null) {
            INSTANCE = new AskTableDialog(null, tableList); 
            INSTANCE.getContentPane().setBackground(new java.awt.Color(255,255,255));
            INSTANCE.setLocationRelativeTo(null);
        }
        return INSTANCE;
    }
    
    private AskTableDialog(java.awt.Frame parent, List<Tables> tableList) {
        super(parent, true);
        this.tableList = tableList;
        this.allTablesComboBoxModel = new TablesComboBoxModel(this.tableList);
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableListComboBox = new javax.swing.JComboBox<>();
        chooseTableButton = new org.jdesktop.swingx.JXButton();
        descriptionPane = new javax.swing.JPanel();
        descriptionLabel = new org.jdesktop.swingx.JXLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("INFEST: Customer >> Set Active Table");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0xffffff));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/com/jogjadamai/infest/assets/InfestIcon.png")).getImage());
        setName("askTableDialog"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        tableListComboBox.setModel(allTablesComboBoxModel);
        tableListComboBox.setToolTipText("Choose table to activate.");
        tableListComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tableListComboBoxItemStateChanged(evt);
            }
        });
        tableListComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableListComboBoxActionPerformed(evt);
            }
        });

        chooseTableButton.setText("Choose");
        chooseTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseTableButtonActionPerformed(evt);
            }
        });

        descriptionPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Table Description"));
        descriptionPane.setToolTipText("Description Pane.");
        descriptionPane.setOpaque(false);

        descriptionLabel.setText("<html>" + "" + "</html>");
        descriptionLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        descriptionLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        descriptionLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout descriptionPaneLayout = new javax.swing.GroupLayout(descriptionPane);
        descriptionPane.setLayout(descriptionPaneLayout);
        descriptionPaneLayout.setHorizontalGroup(
            descriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descriptionPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        descriptionPaneLayout.setVerticalGroup(
            descriptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descriptionPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tableListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(chooseTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void tableListComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tableListComboBoxItemStateChanged
        selectedTable = this.tableList.get(tableListComboBox.getSelectedIndex());
        setTableDescription(selectedTable.getDescription());
    }//GEN-LAST:event_tableListComboBoxItemStateChanged

    private void chooseTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseTableButtonActionPerformed
        Customer controller = Customer.getInstance();
        if(selectedTable != null || tableListComboBox.getSelectedIndex() != -1) {
            controller.activeTable = selectedTable;
            controller.askTable();
            dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                    "You must set the Table for this Customer!",
                    getTitle(), 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_chooseTableButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Customer controller = Customer.getInstance();
        if(controller.activeTable == null) controller.shutdown();
    }//GEN-LAST:event_formWindowClosed

    private void tableListComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableListComboBoxActionPerformed
//        chooseTableButtonActionPerformed(evt);
    }//GEN-LAST:event_tableListComboBoxActionPerformed

    private void setTableDescription(String tableDescription) {
        this.descriptionLabel.setText("<html>" + tableDescription + "</html>");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton chooseTableButton;
    private org.jdesktop.swingx.JXLabel descriptionLabel;
    private javax.swing.JPanel descriptionPane;
    private javax.swing.JComboBox<String> tableListComboBox;
    // End of variables declaration//GEN-END:variables
}
